### ISSUE TITLE
[BUG] - TypeError: a[qt(...)][s.backgroundColor] is not a function

### ISSUE THREAD

**Issue by Forge36** [org-roam/org-roam-ui#290]
**Describe the bug**
>Application error: a client-side exception has occurred (see the browser console for more information).
Top of stack (remainder at bottom)

>TypeError: a[qt(...)][s.backgroundColor] is not a function
    at node (index-f97770bc257e872f8c86.js:1:106141)

**To Reproduce**
Which specific things did you do which lead to said bug? E.g. what did you click, which commands did you call, etc.
1. Go to Settings
2. Expand "visual
3. Click on "Background"
4. Pick the red color, pick the upper-left (black?)
5. Refresh page
7. See nodes fail to load
 
**Expected behavior**
Everything should load without console errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/30872404/233846923-90734977-f083-4911-923c-473949ba48b2.png)

**What browser were you using?**
Chrome - 112.0.5615.138 (Official Build) (64-bit)

**Additional context**
> amework-a62d654bd9699da79f2a.js:1 TypeError: a[qt(...)][s.backgroundColor] is not a function
    at node (index-f97770bc257e872f8c86.js:1:106141)
    at nodeColor (index-f97770bc257e872f8c86.js:1:106161)
    at 879-09bfd8a9d59d1f41b6f4.js:1:1145521
    at Array.forEach (<anonymous>)
    at 879-09bfd8a9d59d1f41b6f4.js:1:1145270
    at Function.tickFrame (879-09bfd8a9d59d1f41b6f4.js:1:1145670)
    at Object.keys.forEach.o.<computed> [as tickFrame] (879-09bfd8a9d59d1f41b6f4.js:1:556634)
    at e (879-09bfd8a9d59d1f41b6f4.js:1:1163032)
    at Function.init (879-09bfd8a9d59d1f41b6f4.js:1:1163157)
    at a (879-09bfd8a9d59d1f41b6f4.js:1:556060)
uu @ framework-a62d654bd9699da79f2a.js:1
main-80dde85f3cea1551bba1.js:1 TypeError: a[qt(...)][s.backgroundColor] is not a function
    at node (index-f97770bc257e872f8c86.js:1:106141)
    at nodeColor (index-f97770bc257e872f8c86.js:1:106161)
    at 879-09bfd8a9d59d1f41b6f4.js:1:1145521
    at Array.forEach (<anonymous>)
    at 879-09bfd8a9d59d1f41b6f4.js:1:1145270
    at Function.tickFrame (879-09bfd8a9d59d1f41b6f4.js:1:1145670)
    at Object.keys.forEach.o.<computed> [as tickFrame] (879-09bfd8a9d59d1f41b6f4.js:1:556634)
    at e (879-09bfd8a9d59d1f41b6f4.js:1:1163032)
    at Function.init (879-09bfd8a9d59d1f41b6f4.js:1:1163157)
    at a (879-09bfd8a9d59d1f41b6f4.js:1:556060)
le @ main-80dde85f3cea1551bba1.js:1
main-80dde85f3cea1551bba1.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
le @ main-80dde85f3cea1551bba1.js:1
index-f97770bc257e872f8c86.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'd3Force')
    at index-f97770bc257e872f8c86.js:1:102480
    at l (main-80dde85f3cea1551bba1.js:1:72073)
    at Generator._invoke (main-80dde85f3cea1551bba1.js:1:71861)
    at Generator.next (main-80dde85f3cea1551bba1.js:1:72502)
    at r (879-09bfd8a9d59d1f41b6f4.js:1:1371690)
    at s (879-09bfd8a9d59d1f41b6f4.js:1:1371893)

**Comment by Forge36** [comment]
I'm working around this with: `Dev Tools → Application → Storage` and clicking "clear site storage"
