### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by Hellseher** [org-roam/org-roam-ui#36]
org-roam-ui:  6f555f6ea6233875fd7e9a7e9041ab7c2df44664
doom-emacs: develop dd55ebb67a51c73939a606159f55fffbd38bed47

_.doom.d/package.el_

```
(package! websocket)
(package! org-roam-ui
  :recipe
  (:host github
   :repo "org-roam/org-roam-ui"
   :files ("*.el" "out")))
```

* Issue

```
Failed to load resource: the server responded with a status of 404 (Not Found)
_buildManifest.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
_ssgManifest.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
workbox-ea903bce.js:12 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:35901/_next/static/chunks/4.2dee5d830195ddd06029.js","status":404}]
    at M.B (http://localhost:35901/workbox-ea903bce.js:710:15)
    at async M.U (http://localhost:35901/workbox-ea903bce.js:699:60)
    at async M.v (http://localhost:35901/workbox-ea903bce.js:392:19)
```

**Comment by ThomasFKJorna** [comment]
Please delete the keys in Application > Local Storage or Storage > Local Storage in the developer settings of your browser, should work agian

**Comment by Hellseher** [comment]
It's resolved with latest pull. Thanks.
